import GenericCard from '@/components/genericcard'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Aula_React_1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.home}>
        <section>
          <h1 className={styles.h1}>Site da Aula de react</h1>
          <h4 className={styles.h4}>eita nois</h4>
        </section>
        <section>
          <GenericCard nome='Hamburguer classico' descricao='O mais disputado entre nossos clientes' imagem= "/Hamburguer-umami01-scaled.jpg"/>
        </section>
      </main>
    </>
  )
}
